### ISSUE TITLE
[language-git] Warnings are not being highlighted

### ISSUE THREAD

**Issue by RishitKedia** [carloscuesta/material-syntax#5]
## User Info

- **Atom:** v1.14.4
- **OS:** macOS Sierra v10.12.3

---

Hey, Carlos! 👋 

First off, I'd like to say that this syntax theme is beautiful, and it's a treat to work with this theme. 👌 

## Issue

While writing a commit message, warnings (for example, when the subject line goes beyond 50 characters) are not being highlighted. 😔 

Material Dark: 

<img width="1415" alt="material-dark" src="https://cloud.githubusercontent.com/assets/7033218/23645460/95860654-0325-11e7-96df-742438903ac3.png">

One Dark: 

<img width="1421" alt="one-dark" src="https://cloud.githubusercontent.com/assets/7033218/23645469/a6b5d71a-0325-11e7-9bcd-85e9ca991e25.png">

## Solution

Adding the following in /styles/base.less 

```
.syntax--invalid {
    &.syntax--illegal {
        background-color: @red;
        color: @white;
    }

    &.syntax--deprecated {
        background-color: @orange;
        color: @white;
    }
}
```

instead of [lines 141-144](https://github.com/carloscuesta/material-syntax/blob/master/styles/base.less#L141) 

```
.syntax--invalid.syntax--illegal {
    background-color: @red;
    color: @white;
}
```

fixes the issue. 😎 

<img width="1422" alt="material-dark-fix" src="https://cloud.githubusercontent.com/assets/7033218/23645405/54ab8032-0325-11e7-8323-cfbe40cba81d.png">

## Pull Request

Carlos, I can create a PR for this if you say so. 💪 

Cheers, 
Rishit

**Comment by carloscuesta** [comment]
Hey @RishitKedia!

Thanks for submitting this issue, (the best one I've ever seen 🎉). Never noticed that warning section inside of language-git.

Please, feel free to send a pull request 👍

**Comment by RishitKedia** [comment]
Thanks, Carlos! I'll create a PR for this right away! 👍 😃
