### ISSUE TITLE
GraphQL Support

### ISSUE THREAD

**Issue by RishitKedia** [carloscuesta/material-syntax#9]
Hey, Carlos! 👋 

It'd be great if `Sprinkles` could support [`language-graphql`](https://github.com/rmosolgo/language-graphql). 💪 

Thanks! 😃

**Comment by carloscuesta** [comment]
Cool! Will take a look, feel free to send a PR 🎉

**Comment by RishitKedia** [comment]
Hey, Carlos! 😃

I've moved on to `Visual Studio Code` from `Atom`, so please feel free to close this issue. 😋

Missing this theme, BTW! Haven't found anything similar for `vscode`. 😭 Would love one for `vscode` too. 😜 Still loving `materialshell`, though.

Cheers! 🙏
